// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaTarefas.Data;

#nullable disable

namespace SistemaTarefas.Migrations
{
    [DbContext(typeof(SistemaTarefasDBContex))]
    [Migration("20251030005108_DB20251018")]
    partial class DB20251018
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaTarefas.DTO.Query.ModelosTramiteSQL", b =>
                {
                    b.Property<string>("MtarDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtarNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtraDescricaoTramite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MtraDuracaoPrevistaDias")
                        .HasColumnType("int");

                    b.Property<int>("MtraId")
                        .HasColumnType("int");

                    b.Property<int>("MtraMtarId")
                        .HasColumnType("int");

                    b.Property<string>("MtraNomeTramite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MtraOrdem")
                        .HasColumnType("int");

                    b.Property<int?>("MtraUsuIdIndicacao")
                        .HasColumnType("int");

                    b.Property<int?>("MtraUsuIdRevisor")
                        .HasColumnType("int");

                    b.Property<string>("UsuNomeIndicacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuNomeRevisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.DTO.Query.TarefasSQL", b =>
                {
                    b.Property<string>("FlaCor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlaRotulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtarDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtarNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TarDataComeco")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TarDataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarDataFinalPrevista")
                        .HasColumnType("datetime2");

                    b.Property<string>("TarDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TarFlaId")
                        .HasColumnType("int");

                    b.Property<int>("TarId")
                        .HasColumnType("int");

                    b.Property<int>("TarMtarId")
                        .HasColumnType("int");

                    b.Property<string>("TarNomeTarefa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TarUsuIdResponsavelTarefa")
                        .HasColumnType("int");

                    b.Property<string>("UsuNomeUsuarioResponsavelTarefa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.DTO.Query.TramitesSQL", b =>
                {
                    b.Property<string>("FlaCor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlaRotulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtarDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtarNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtraDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtraNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TarDataComeco")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TarDataFinalPrevista")
                        .HasColumnType("datetime2");

                    b.Property<string>("TarDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TarFlaId")
                        .HasColumnType("int");

                    b.Property<int>("TarMtarId")
                        .HasColumnType("int");

                    b.Property<string>("TarNomeTarefa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TraDataExecucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TraDataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TraDataPrevisaoTermino")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TraDataRevisao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraId")
                        .HasColumnType("int");

                    b.Property<int>("TraMtraId")
                        .HasColumnType("int");

                    b.Property<string>("TraNotaRevisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraNotaTramitador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TraOrdem")
                        .HasColumnType("int");

                    b.Property<bool>("TraRepetido")
                        .HasColumnType("bit");

                    b.Property<int>("TraStatus")
                        .HasColumnType("int");

                    b.Property<int>("TraTarId")
                        .HasColumnType("int");

                    b.Property<int?>("TraUsuIdRevisor")
                        .HasColumnType("int");

                    b.Property<int?>("TraUsuIdTramitador")
                        .HasColumnType("int");

                    b.Property<string>("UsuNomeResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuNomeRevisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuNomeTramitador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tarUsuIdResponsavelTarefa")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Models.Flags", b =>
                {
                    b.Property<int>("FlaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FLA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlaId"));

                    b.Property<string>("FlaCor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("FLA_COR");

                    b.Property<string>("FlaRotulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FLA_ROTULO");

                    b.HasKey("FlaId");

                    b.HasIndex("FlaCor")
                        .IsUnique()
                        .HasDatabaseName("IX_Cor");

                    b.HasIndex("FlaRotulo")
                        .IsUnique()
                        .HasDatabaseName("IX_Rotulo");

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Models.ModelosTarefa", b =>
                {
                    b.Property<int>("MtarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MTAR_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MtarId"));

                    b.Property<string>("MtarDescricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MTAR_Descricao");

                    b.Property<string>("MtarNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MTAR_Nome");

                    b.HasKey("MtarId")
                        .HasName("PK_ModelosTarefa");

                    b.HasIndex("MtarNome")
                        .IsUnique()
                        .HasDatabaseName("IX_ModelosTarefa_MTAR_Nome_UNIQUE");

                    b.ToTable("ModelosTarefa", (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Models.ModelosTramite", b =>
                {
                    b.Property<int>("MtraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MTRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MtraId"));

                    b.Property<int?>("ModelosTarefaMtarId")
                        .HasColumnType("int");

                    b.Property<string>("MtraDescricaoTramite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MTRA_DescricaoTramite");

                    b.Property<int>("MtraDuracaoPrevistaDias")
                        .HasColumnType("int")
                        .HasColumnName("MTRA_DuracaoPrevistaDias");

                    b.Property<int>("MtraMtarId")
                        .HasColumnType("int")
                        .HasColumnName("MTRA_MTAR_ID");

                    b.Property<string>("MtraNomeTramite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MTRA_NomeTramite");

                    b.Property<int>("MtraOrdem")
                        .HasColumnType("int")
                        .HasColumnName("MTRA_Ordem");

                    b.Property<int?>("MtraUsuIdIndicacao")
                        .HasColumnType("int")
                        .HasColumnName("MTRA_USU_ID_Indicacao");

                    b.Property<int?>("MtraUsuIdRevisor")
                        .HasColumnType("int")
                        .HasColumnName("MTRA_USU_ID_Revisor");

                    b.Property<int?>("TraMtarTraId")
                        .HasColumnType("int");

                    b.HasKey("MtraId")
                        .HasName("PK_TramitesTiposTarefa");

                    b.HasIndex("ModelosTarefaMtarId");

                    b.HasIndex("MtraMtarId");

                    b.HasIndex("MtraUsuIdIndicacao");

                    b.HasIndex("MtraUsuIdRevisor");

                    b.HasIndex("TraMtarTraId");

                    b.ToTable("ModelosTramite", (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Models.Tarefas", b =>
                {
                    b.Property<int>("TarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TAR_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarId"));

                    b.Property<DateTime>("TarDataComeco")
                        .HasColumnType("datetime2")
                        .HasColumnName("TAR_DataComeco");

                    b.Property<DateTime?>("TarDataFinal")
                        .HasColumnType("datetime2")
                        .HasColumnName("TAR_DataFinal");

                    b.Property<DateTime?>("TarDataFinalPrevista")
                        .HasColumnType("datetime2")
                        .HasColumnName("TAR_DataFinalPrevista");

                    b.Property<string>("TarDescricao")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TAR_Descricao");

                    b.Property<int?>("TarFlaId")
                        .HasColumnType("int")
                        .HasColumnName("TAR_FLA_ID");

                    b.Property<int>("TarMtarId")
                        .HasColumnType("int")
                        .HasColumnName("TAR_MTAR_ID");

                    b.Property<string>("TarNomeTarefa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TAR_Nome");

                    b.Property<string>("TarStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("TAR_Status");

                    b.Property<int>("TarUsuIdResponsavelTarefa")
                        .HasColumnType("int")
                        .HasColumnName("TAR_USU_ID_Responsavel");

                    b.HasKey("TarId")
                        .HasName("PK_Tarefa");

                    b.HasIndex("TarFlaId");

                    b.HasIndex("TarMtarId");

                    b.HasIndex("TarNomeTarefa")
                        .IsUnique()
                        .HasDatabaseName("IX_Tarefa_TAR_Nome_UNIQUE");

                    b.HasIndex("TarUsuIdResponsavelTarefa");

                    b.ToTable("Tarefas", (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuId"));

                    b.Property<DateTime>("UsuDataMudancaSenha")
                        .HasColumnType("datetime2")
                        .HasColumnName("USU_DataMudancaSenha");

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("USU_Email");

                    b.Property<string>("UsuImagemPerfil")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("USU_ImagemPerfil");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USU_Login");

                    b.Property<string>("UsuMatricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("USU_Matricula");

                    b.Property<int>("UsuNivel")
                        .HasColumnType("int")
                        .HasColumnName("USU_Nivel");

                    b.Property<string>("UsuNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USU_Nome");

                    b.Property<string>("UsuSenha")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("USU_Senha");

                    b.HasKey("UsuId");

                    b.HasIndex("UsuLogin")
                        .IsUnique()
                        .HasDatabaseName("IX_Login");

                    b.HasIndex("UsuMatricula")
                        .IsUnique()
                        .HasDatabaseName("IX_Matricula");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuId = 1,
                            UsuDataMudancaSenha = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuEmail = "mail@mail.com",
                            UsuImagemPerfil = "",
                            UsuLogin = "admin",
                            UsuMatricula = "000000",
                            UsuNivel = 1,
                            UsuNome = "Administrador do Sistema",
                            UsuSenha = "$2a$11$a00iJK2u54s2C7RA/M4kjevS563lW2yS8zd.KcWWxbuFsHWqfjA1."
                        });
                });

            modelBuilder.Entity("Tramites", b =>
                {
                    b.Property<int>("TraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraId"));

                    b.Property<DateTime?>("TraDataExecucao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRA_DataExecucao");

                    b.Property<DateTime>("TraDataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRA_DataInicio");

                    b.Property<DateTime>("TraDataPrevisaoTermino")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRA_DataPrevisaoTermino");

                    b.Property<DateTime?>("TraDataRevisao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRA_DataRevisao");

                    b.Property<int>("TraMtraId")
                        .HasColumnType("int")
                        .HasColumnName("TRA_MTRA_ID");

                    b.Property<string>("TraNotaRevisor")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TRA_NotaRevisor");

                    b.Property<string>("TraNotaTramitador")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TRA_NotaTramitador");

                    b.Property<int>("TraOrdem")
                        .HasColumnType("int")
                        .HasColumnName("TRA_Ordem");

                    b.Property<bool>("TraRepetido")
                        .HasColumnType("bit")
                        .HasColumnName("TRA_TramiteRepetido");

                    b.Property<int>("TraStatus")
                        .HasColumnType("int")
                        .HasColumnName("TRA_Status");

                    b.Property<int>("TraTarId")
                        .HasColumnType("int")
                        .HasColumnName("TRA_TAR_ID");

                    b.Property<int?>("TraUsuIdRevisor")
                        .HasColumnType("int")
                        .HasColumnName("TRA_USU_ID_Revisor");

                    b.Property<int?>("TraUsuIdTramitador")
                        .HasColumnType("int")
                        .HasColumnName("TRA_USU_ID_Tramitador");

                    b.HasKey("TraId")
                        .HasName("PK_Tramite");

                    b.HasIndex("TraMtraId");

                    b.HasIndex("TraTarId");

                    b.HasIndex("TraUsuIdRevisor");

                    b.HasIndex("TraUsuIdTramitador");

                    b.ToTable("Tramites", (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Models.ModelosTramite", b =>
                {
                    b.HasOne("SistemaTarefas.Models.ModelosTarefa", null)
                        .WithMany("ModelosTramite")
                        .HasForeignKey("ModelosTarefaMtarId");

                    b.HasOne("SistemaTarefas.Models.ModelosTramite", "MtraMtarNavigation")
                        .WithMany("TramitesTiposTarefa")
                        .HasForeignKey("MtraMtarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Modelos_Tramite");

                    b.HasOne("SistemaTarefas.Models.Usuarios", "MtraUsuIdIndicacaoNavigation")
                        .WithMany("TramitesTipoTarefaIndicacao")
                        .HasForeignKey("MtraUsuIdIndicacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Modelos_Tramite_Usuarios_Indicacao");

                    b.HasOne("SistemaTarefas.Models.Usuarios", "MtraUsuIdResponsavelNavigation")
                        .WithMany("TramitesTipoTarefaResponsavel")
                        .HasForeignKey("MtraUsuIdRevisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Modeos_Tramite_Usuarios_Responsavel");

                    b.HasOne("Tramites", "TraMtar")
                        .WithMany()
                        .HasForeignKey("TraMtarTraId");

                    b.Navigation("MtraMtarNavigation");

                    b.Navigation("MtraUsuIdIndicacaoNavigation");

                    b.Navigation("MtraUsuIdResponsavelNavigation");

                    b.Navigation("TraMtar");
                });

            modelBuilder.Entity("SistemaTarefas.Models.Tarefas", b =>
                {
                    b.HasOne("SistemaTarefas.Models.Flags", "TarFlaIdNavigation")
                        .WithMany("Tarefas")
                        .HasForeignKey("TarFlaId")
                        .HasConstraintName("FK_Tarefas_Flags");

                    b.HasOne("SistemaTarefas.Models.ModelosTarefa", "TarMtar")
                        .WithMany("Tarefas")
                        .HasForeignKey("TarMtarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tarefas_Modelos_Tarefa");

                    b.HasOne("SistemaTarefas.Models.Usuarios", "TarUsuIdResponsavelTarefaNavigation")
                        .WithMany("Tarefas")
                        .HasForeignKey("TarUsuIdResponsavelTarefa")
                        .IsRequired()
                        .HasConstraintName("FK_Tarefas_Usuarios");

                    b.Navigation("TarFlaIdNavigation");

                    b.Navigation("TarMtar");

                    b.Navigation("TarUsuIdResponsavelTarefaNavigation");
                });

            modelBuilder.Entity("Tramites", b =>
                {
                    b.HasOne("SistemaTarefas.Models.ModelosTramite", "TraTttIdNavigation")
                        .WithMany("Tramites")
                        .HasForeignKey("TraMtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Modelos_Tramites");

                    b.HasOne("SistemaTarefas.Models.Tarefas", "TraTarIdNavigation")
                        .WithMany("Tramites")
                        .HasForeignKey("TraTarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tramites_Tarefas");

                    b.HasOne("SistemaTarefas.Models.Usuarios", "TraUsuIdRevisorNavigation")
                        .WithMany("TramitesRevisor")
                        .HasForeignKey("TraUsuIdRevisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Tramites_UsuariosRevisor");

                    b.HasOne("SistemaTarefas.Models.Usuarios", "TraUsuIdTramitadorNavigation")
                        .WithMany("TramitesTramitador")
                        .HasForeignKey("TraUsuIdTramitador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Tramites_UsuariosTramitador");

                    b.Navigation("TraTarIdNavigation");

                    b.Navigation("TraTttIdNavigation");

                    b.Navigation("TraUsuIdRevisorNavigation");

                    b.Navigation("TraUsuIdTramitadorNavigation");
                });

            modelBuilder.Entity("SistemaTarefas.Models.Flags", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("SistemaTarefas.Models.ModelosTarefa", b =>
                {
                    b.Navigation("ModelosTramite");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("SistemaTarefas.Models.ModelosTramite", b =>
                {
                    b.Navigation("Tramites");

                    b.Navigation("TramitesTiposTarefa");
                });

            modelBuilder.Entity("SistemaTarefas.Models.Tarefas", b =>
                {
                    b.Navigation("Tramites");
                });

            modelBuilder.Entity("SistemaTarefas.Models.Usuarios", b =>
                {
                    b.Navigation("Tarefas");

                    b.Navigation("TramitesRevisor");

                    b.Navigation("TramitesTipoTarefaIndicacao");

                    b.Navigation("TramitesTipoTarefaResponsavel");

                    b.Navigation("TramitesTramitador");
                });
#pragma warning restore 612, 618
        }
    }
}
